"""
# ==============================================================================
# LABORATORY: APPROXIMATION ALGORITHMS (TSP 2-APPROXIMATION)
# ==============================================================================
#
# 1. WHY THIS MATTERS
# -------------------
# You learned that the Traveling Salesperson Problem (TSP) is NP-Hard. 
# - Backtracking takes $O(N!)$.
# - Dynamic Programming takes $O(N^2 2^N)$.
# - Branch and Bound takes exponential time in the worst case.
#
# What if Amazon needs to calculate a delivery route for 10,000 packages?
# $10,000!$ is a number so large it breaks physics. ALL exact algorithms fail.
#
# The Solution: Approximation Algorithms!
# In the real world, we do not need the absolute mathematically perfect route. 
# We just need a route that is "Good Enough", calculated incredibly fast!
#
# The 2-Approximation MST Algorithm:
# If the city distances obey the Triangle Inequality (meaning a direct flight 
# from A to C is always faster or equal to A -> B -> C), we can use a brilliant 
# mathematical shortcut:
# 
# 1. Calculate the Minimum Spanning Tree (MST) of the graph using Prim's or Kruskal's.
# 2. Perform a Preorder DFS Traversal of the MST.
# 3. The path generated by that traversal is mathematically GUARANTEED to be 
#    no worse than exactly 2x the cost of the absolute perfect optimal tour!
#
# Time Complexity: $O(E \log V)$ (The speed of finding the MST).
# We solve the 10,000 city route in a fraction of a second, with a mathematical 
# guarantee that our delivery trucks will drive, at absolute worst, double the 
# optimal mileage. (In practice, it is usually within 1.2x of optimal).
#
# 2. LEARNING OBJECTIVES
# ----------------------
# - Understand Metric Graphs (Triangle Inequality).
# - Construct a TSP Approximation using Minimum Spanning Trees.
# - Prove the 2x Upper Bound guarantee.
#
# ==============================================================================
"""

import math
from typing import List, Tuple, Dict, Set
import heapq

def section_header(title: str) -> None:
    print(f"\n{'='*60}\n{title.upper()}\n{'='*60}")


# ==============================================================================
# 3. GRAPH ENGINE (METRIC SPACES)
# ==============================================================================
# We define a Point in 2D space. The Euclidean distance between 2D points 
# naturally perfectly obeys the Triangle Inequality!
Point = Tuple[float, float]

def get_distance(p1: Point, p2: Point) -> float:
    return math.sqrt((p1[0] - p2[0])**2 + (p1[1] - p2[1])**2)


# ==============================================================================
# 4. MST 2-APPROXIMATION ALGORITHM
# ==============================================================================
def approximate_tsp_mst(points: List[Point]) -> Tuple[float, List[int]]:
    """
    Calculates a route that visits all points and returns to the start.
    Guaranteed to be <= 2x the cost of the absolute optimal tour!
    Time Complexity: O(V^2) for dense graphs using Prim's Algorithm.
    """
    n = len(points)
    if n <= 1:
        return 0.0, [0] if n == 1 else []
        
    # 1. PRIM'S ALGORITHM (Calculate the Minimum Spanning Tree)
    # We want to find the absolute cheapest set of edges that connects all nodes.
    mst_adj: Dict[int, List[int]] = {i: [] for i in range(n)}
    
    visited = [False] * n
    # Min-Heap stores (distance_to_node, node_id, parent_node_id)
    # We start at Node 0.
    pq = [(0.0, 0, -1)]
    
    edges_added = 0
    while pq and edges_added < n:
        dist, u, parent = heapq.heappop(pq)
        
        if visited[u]:
            continue
            
        visited[u] = True
        edges_added += 1
        
        # If this is not the root node, add the edge to our MST graph!
        if parent != -1:
            mst_adj[u].append(parent)
            mst_adj[parent].append(u)
            
        # Explore all unvisited neighbors
        # (Since it's a fully connected 2D plane, every node connects to every node)
        for v in range(n):
            if not visited[v]:
                weight = get_distance(points[u], points[v])
                heapq.heappush(pq, (weight, v, u))
                
    # 2. PREORDER DFS TRAVERSAL OF THE MST
    # We start at the root (Node 0) and walk the spanning tree.
    tsp_path = []
    dfs_visited = [False] * n
    
    def preorder_dfs(node: int):
        dfs_visited[node] = True
        tsp_path.append(node)
        
        for neighbor in mst_adj[node]:
            if not dfs_visited[neighbor]:
                preorder_dfs(neighbor)
                
    preorder_dfs(0)
    
    # Complete the cycle by returning to the start!
    tsp_path.append(0)
    
    # 3. CALCULATE THE TOTAL COST OF THIS APPROXIMATION TOUR
    total_cost = 0.0
    for i in range(len(tsp_path) - 1):
        u = tsp_path[i]
        v = tsp_path[i + 1]
        total_cost += get_distance(points[u], points[v])
        
    return total_cost, tsp_path


def demonstrate_approximation():
    section_header("Algorithm: TSP 2-Approximation (MST Method)")
    
    # 6 cities located on a 2D grid
    cities = [
        (0.0, 0.0),    # City 0
        (10.0, 0.0),   # City 1
        (10.0, 10.0),  # City 2
        (0.0, 10.0),   # City 3
        (5.0, 5.0),    # City 4 (Center)
        (2.0, 8.0)     # City 5
    ]
    
    print(f"Tracking {len(cities)} Amazon Delivery Destinations...")
    print("Executing MST DFS Preorder Approximation in O(V^2)...")
    
    approx_cost, approx_route = approximate_tsp_mst(cities)
    
    print(f"\nApproximated Tour Route: {' -> '.join(map(str, approx_route))}")
    print(f"Approximated Tour Cost : {approx_cost:.2f}")
    
    print("\nMathematical Guarantee:")
    print("Because these points are on a 2D Euclidean grid (Metric Space), the ")
    print("Triangle Inequality holds true. The absolute mathematically perfect ")
    print("route is strictly guaranteed to be NO LESS THAN half of our cost!")
    print(f"Absolute Optimal Cost >= {approx_cost / 2.0:.2f}")


# ==============================================================================
# 5. ACTIVE RECALL & INTERVIEW QUESTIONS
# ==============================================================================
"""
ACTIVE RECALL:
1. Why does the Preorder Traversal of an MST create a valid TSP Tour?
   Answer: An MST connects all $V$ vertices using exactly $V-1$ edges without cycles. If you imagine tracing the exact perimeter of the MST (walking down an edge and walking right back up it), you visit every node and travel exactly $2 \times$ the total weight of the MST. 
   A Preorder Traversal skips the "walking back up" part by physically jumping directly to the next unvisited branch (shortcutting). Because of the Triangle Inequality, the shortcut direct flight from Leaf A to Branch B is mathematically guaranteed to be shorter than walking $A \to \text{Root} \to B$.

2. Why is it guaranteed to be $\le 2 \times$ Optimal?
   Answer: 
   - Rule 1: The absolute Optimal TSP Tour is a loop connecting all points. If you remove ONE edge from the Optimal Tour, it becomes a Spanning Tree! Therefore, the cost of the Minimum Spanning Tree is mathematically $\le$ the Optimal TSP Tour!
   - Rule 2: If we trace every edge of the MST twice (down and back up), the cost is $2 \times \text{MST}$. Therefore, tracing the MST twice is $\le 2 \times \text{Optimal Tour}$.
   - Rule 3: Our Preorder DFS uses direct flight shortcuts instead of walking back up edges. Because of the Triangle Inequality, shortcuts make the route SHORTER!
   - Conclusion: Our Route $\le 2 \times \text{MST} \le 2 \times \text{Optimal Tour}$! The proof is flawless.

3. Does this work on ALL graphs?
   Answer: NO! It ONLY works if the graph satisfies the Triangle Inequality (a Metric space). If you have a disconnected graph where a flight from New York to London costs \$500, but a flight from New York to Boston to London costs \$10, the Triangle Inequality is broken. In a Non-Metric graph, TSP cannot be approximated within ANY constant factor unless P = NP! The 2-Approximation completely collapses.
"""

if __name__ == "__main__":
    demonstrate_approximation()
    print("\n[SUCCESS] Laboratory: Approximation Algorithms Completed.")
