import os

# Target file path
TARGET_FILE = r"d:\work\python-all\16-Deep-Learning-and-CV-NLP\11_cv_advanced_vision.md"

# Ensure directory exists
os.makedirs(os.path.dirname(TARGET_FILE), exist_ok=True)

markdown_part1 = """# Chapter 11: Advanced Computer Vision

Welcome to this comprehensive and deep exploration of Advanced Computer Vision (CV). In earlier chapters, we traversed the foundational aspects of image processing, convolutions, and standard Convolutional Neural Networks (CNNs) for image classification. While classification is a critical capability—answering the question "What is in this image?"—it is rarely sufficient for complex, real-world tasks. Autonomous vehicles, medical image analysis, and robotic grasping require much more nuanced spatial awareness. They need to know *where* objects are, *which pixels* belong to which objects, and how different visual elements interact in a global context.

This chapter ventures beyond simple image classification into three primary pillars of modern Advanced Computer Vision:
1. **Object Detection**: Localizing and classifying multiple objects within an image.
2. **Semantic and Instance Segmentation**: Classifying every single pixel to delineate precise object boundaries.
3. **Vision Transformers (ViT)**: Abandoning pure convolutions in favor of self-attention mechanisms to capture long-range dependencies in visual data.

We will dive deep into the architectures, the mathematical formulations, and the foundational algorithms that power these systems. We will compare one-stage vs. two-stage detectors, explore encoder-decoder structures, and break down the matrix mathematics behind ViT patching.

---

## 11.1 Object Detection Foundations

Object detection expands upon classification by introducing localization. We are no longer satisfied with a single probability distribution for an image; instead, we want a list of bounding boxes, each accompanied by a class probability.

### 11.1.1 Bounding Boxes and Regression

A bounding box is traditionally parameterized in one of two ways:
1. **Corner Formulation**: $(x_{min}, y_{min}, x_{max}, y_{max})$ representing the top-left and bottom-right corners.
2. **Center Formulation**: $(x_c, y_c, w, h)$ representing the center coordinate, width, and height of the box.

Object detection networks often use the center formulation because predicting offsets from an anchor or grid cell center tends to be mathematically stabler. The network outputs values $\hat{t}_x, \hat{t}_y, \hat{t}_w, \hat{t}_h$, which are then transformed to predict bounding box coordinates.

### 11.1.2 Intersection Over Union (IoU)

To evaluate how well a predicted bounding box aligns with the ground truth, we use **Intersection over Union (IoU)**, also known as the Jaccard Index.

$$ IoU = \\frac{Area\\ of\\ Overlap}{Area\\ of\\ Union} = \\frac{|B_p \\cap B_{gt}|}{|B_p \\cup B_{gt}|} $$

Where $B_p$ is the predicted bounding box and $B_{gt}$ is the ground truth bounding box.
- An IoU of $0.0$ implies no overlap.
- An IoU of $1.0$ implies a perfect match.
- Typically, an IoU $> 0.5$ is considered a "True Positive" in classical metrics like PASCAL VOC. Modern metrics (like MS COCO) evaluate across a range of IoU thresholds (e.g., $0.50$ to $0.95$).

### 11.1.3 Non-Maximum Suppression (NMS)

Object detectors often predict multiple bounding boxes for the same object due to the dense nature of grid cells or anchor boxes. **Non-Maximum Suppression (NMS)** is the algorithmic filter used to eliminate redundant predictions.

**Algorithm for NMS:**
1. Select the bounding box prediction with the highest confidence score.
2. Remove all other bounding boxes that have an IoU with the selected box greater than a predefined threshold $\\tau_{nms}$.
3. Repeat the process for the remaining boxes until no boxes are left unprocessed.

Soft-NMS is a modern variant that, instead of completely suppressing boxes, decays their confidence score based on their IoU with the highest-scoring box, which helps preserve heavily occluded objects.

---

## 11.2 Object Detection Architectures

Historically, object detection models have been bifurcated into two paradigms: **Two-Stage Detectors** and **One-Stage Detectors**.

### 11.2.1 Two-Stage Detectors: R-CNN to Faster R-CNN

Two-stage detectors generate region proposals first and then classify/refine them. They are traditionally known for high accuracy but slower inference speeds.

#### R-CNN (Regions with CNN features)
The original R-CNN used Selective Search to extract ~2,000 region proposals from an image. Each region was warped to a fixed size and fed independently through a CNN (like AlexNet) to extract features, which were then classified using an SVM. This was notoriously slow because the CNN ran 2,000 times per image.

#### Fast R-CNN
Fast R-CNN solved the bottleneck of R-CNN by running the CNN over the *entire image once* to produce a global feature map. Region proposals (still generated by Selective Search) were projected onto this feature map. A novel operation called **RoI (Region of Interest) Pooling** extracted fixed-size feature vectors from these varied-size proposals, passing them to fully connected layers for classification and bounding box regression.

#### Faster R-CNN
Faster R-CNN eliminated the slow Selective Search algorithm entirely. It introduced the **Region Proposal Network (RPN)**, a fully convolutional network that shares convolutional layers with the detection network.
The RPN slides a small window over the feature map. At each sliding window location, it predicts multiple region proposals parameterized relative to reference boxes called **Anchors**. 
The loss function for Faster R-CNN is a multi-task loss incorporating both the RPN and the Fast R-CNN head:

$$ L(p, u, t^u, v) = L_{cls}(p, u) + \\lambda [u \\ge 1] L_{loc}(t^u, v) $$

where $p$ is the predicted class probability, $u$ is the true class, $t^u$ is the predicted bounding box translation, and $v$ is the true bounding box translation.

### 11.2.2 One-Stage Detectors: YOLO Architecture

**YOLO (You Only Look Once)** revolutionized object detection by reframing it as a single regression problem, moving straight from image pixels to bounding box coordinates and class probabilities.

#### Grid Cell Formulation
YOLO divides the input image into an $S \\times S$ grid. If the center of an object falls into a grid cell, that grid cell is responsible for detecting that object.
Each grid cell predicts $B$ bounding boxes and confidence scores for those boxes, as well as $C$ conditional class probabilities.

The confidence score is defined as:
$$ Confidence = Pr(Object) \\times IoU_{pred}^{truth} $$

For each bounding box, the network predicts 5 values: $x, y, w, h$, and $confidence$.
The total output tensor size is $S \\times S \\times (B \\times 5 + C)$.

#### YOLO Loss Function
YOLO's loss function is highly engineered. It uses Sum of Squared Errors (SSE) because it is easy to optimize, but it weighs different components to balance the learning:
1. **Coordinate Loss**: Penalizes errors in bounding box dimensions. It uses the square root of width and height to penalize small deviations in small boxes more heavily than in large boxes.
2. **Confidence Loss (Object present)**: Heavily penalized if an object is present but confidence is low.
3. **Confidence Loss (No Object)**: Uses a scaling factor ($\\lambda_{noobj} = 0.5$) to down-weight the loss for cells containing no objects, preventing them from overpowering the gradients.
4. **Classification Loss**: Standard classification error for the cell.

```python
# A conceptual snippet of a YOLO-style output processing in PyTorch
import torch
import torch.nn as nn

class YOLOLayer(nn.Module):
    def __init__(self, S=7, B=2, C=20):
        super(YOLOLayer, self).__init__()
        self.S = S
        self.B = B
        self.C = C
        
    def forward(self, x):
        # x is the output tensor from the darknet feature extractor
        # shape: (batch_size, S*S*(B*5 + C))
        batch_size = x.size(0)
        
        # Reshape to (batch, S, S, B*5 + C)
        x = x.view(batch_size, self.S, self.S, self.B * 5 + self.C)
        
        # Split into bounding boxes, confidence, and classes
        # ... logic for parsing predictions, applying sigmoid to confidence, etc.
        return x
```

Modern iterations (YOLOv4, YOLOv8, YOLOX) introduce mosaic data augmentation, cross-stage partial connections (CSPNet), anchor-free detection mechanisms, and advanced label assignment strategies (like SimOTA), making them incredibly fast and robust for real-time edge deployment.

---

## 11.3 Semantic and Instance Segmentation

While bounding boxes are excellent for general localization, they contain a lot of background noise. In domains like autonomous driving (distinguishing drivable space from sidewalk) or medical imaging (delineating a tumor), we need pixel-perfect boundaries. This is the domain of **Segmentation**.

### 11.3.1 Semantic Segmentation

Semantic segmentation treats the task as a dense classification problem: every pixel is assigned a class label. However, it does not distinguish between different instances of the same object class. If two cars overlap, they merge into a single "car" blob of pixels.

The fundamental challenge in semantic segmentation is that standard CNNs use pooling layers to increase the receptive field, which drastically reduces spatial resolution. We need both deep semantic features (what the object is) and high spatial resolution (where its exact boundaries are).

### 11.3.2 Fully Convolutional Networks (FCNs)

FCNs popularized the idea of replacing dense (fully connected) layers at the end of a CNN with $1 \\times 1$ convolutions, allowing the network to output spatial maps rather than 1D vectors. To recover spatial resolution, FCNs use **Transposed Convolutions** (often incorrectly called deconvolutions) to upsample the feature maps. FCNs also introduced "skip connections" to combine coarse, high-layer information with fine, low-layer information.

### 11.3.3 The U-Net Architecture

The **U-Net** is arguably the most famous architecture for semantic segmentation, originally designed for biomedical image segmentation but now ubiquitous across domains.

U-Net's architecture is shaped like a 'U' and consists of two parts:
1. **Contracting Path (Encoder)**: Captures context. It consists of repeated blocks of two $3 \\times 3$ convolutions followed by a ReLU and a $2 \\times 2$ max pooling operation with stride 2 for downsampling. At each downsampling step, the number of feature channels is doubled.
2. **Expansive Path (Decoder)**: Enables precise localization. Every step consists of an upsampling of the feature map (via a $2 \\times 2$ transposed convolution), a **concatenation** with the correspondingly cropped feature map from the contracting path, and two $3 \\times 3$ convolutions.

The critical innovation is the **Skip Connections**. Unlike standard FCNs which simply add feature maps, U-Net concatenates them. This forces the decoder to explicitly learn how to fuse the high-resolution texture details from the encoder with the deep semantic features of the bottleneck layer.

```python
import torch
import torch.nn as nn
import torch.nn.functional as F

class DoubleConv(nn.Module):
    \"\"\"(convolution => [BN] => ReLU) * 2\"\"\"
    def __init__(self, in_channels, out_channels):
        super().__init__()
        self.double_conv = nn.Sequential(
            nn.Conv2d(in_channels, out_channels, kernel_size=3, padding=1),
            nn.BatchNorm2d(out_channels),
            nn.ReLU(inplace=True),
            nn.Conv2d(out_channels, out_channels, kernel_size=3, padding=1),
            nn.BatchNorm2d(out_channels),
            nn.ReLU(inplace=True)
        )

    def forward(self, x):
        return self.double_conv(x)

class UNet(nn.Module):
    def __init__(self, n_channels, n_classes):
        super(UNet, self).__init__()
        self.inc = DoubleConv(n_channels, 64)
        self.down1 = nn.Sequential(nn.MaxPool2d(2), DoubleConv(64, 128))
        self.down2 = nn.Sequential(nn.MaxPool2d(2), DoubleConv(128, 256))
        
        self.up1 = nn.ConvTranspose2d(256, 128, kernel_size=2, stride=2)
        self.conv_up1 = DoubleConv(256, 128) # 128 + 128 channels concatenated
        
        self.outc = nn.Conv2d(128, n_classes, kernel_size=1)

    def forward(self, x):
        x1 = self.inc(x)
        x2 = self.down1(x1)
        x3 = self.down2(x2)
        
        # Upsampling and Skip Connection
        x = self.up1(x3)
        # Assuming input dimensions are multiples of 4 so no padding/cropping needed
        x = torch.cat([x2, x], dim=1) 
        x = self.conv_up1(x)
        
        logits = self.outc(x)
        return logits
```

### 11.3.4 Instance Segmentation (Mask R-CNN)

Instance segmentation solves the overlapping object problem by differentiating between object instances. **Mask R-CNN** extends Faster R-CNN by adding a parallel branch for predicting segmentation masks on each Region of Interest (RoI).

Crucially, Mask R-CNN replaces RoI Pooling with **RoIAlign**. Standard RoI pooling involves quantization (rounding floating-point coordinates to integer bins), which creates a misalignment between the RoI and the extracted features. While this is fine for bounding box regression, it destroys pixel-level accuracy needed for masks. RoIAlign uses bilinear interpolation to compute exact values of the input features at four regularly sampled locations in each RoI bin, aggregating the result to preserve precise spatial alignment.

---

## 11.4 Vision Transformers (ViT): A Paradigm Shift

For nearly a decade, Convolutional Neural Networks were the undisputed kings of Computer Vision. The inductive bias of convolutions—translation invariance and local neighborhood connectivity—was perfectly suited for processing grid-like image data. However, CNNs struggle to capture long-range global dependencies early in the network; their receptive field only grows gradually through deep pooling layers.

In 2020, Dosovitskiy et al. introduced the **Vision Transformer (ViT)**, demonstrating that a pure Transformer architecture applied directly to sequences of image patches could match or outperform state-of-the-art CNNs, provided it is trained on massive datasets (like JFT-300M).

### 11.4.1 Image Patching and Linear Projection

The standard Transformer expects a 1D sequence of token embeddings as input. An image $x \\in \\mathbb{R}^{H \\times W \\times C}$ cannot be flattened trivially without destroying its 2D structural integrity, and flattening all pixels into a sequence length of $H \\times W$ is computationally intractable for the self-attention mechanism, which scales quadratically $O(N^2)$.

To handle this, ViT reshapes the image into a sequence of flattened 2D patches $x_p \\in \\mathbb{R}^{N \\times (P^2 \\cdot C)}$, where $(P, P)$ is the patch resolution (e.g., $16 \\times 16$), and $N = \\frac{HW}{P^2}$ is the resulting number of patches. This sequence length $N$ serves as the effective input length for the Transformer.

Each patch is then flattened and projected into a constant latent vector size $D$ through a trainable linear projection matrix $\\mathbf{E}$. This linear projection is mathematically equivalent to a standard 2D convolution with both a kernel size and a stride of $P$.

$$ \\mathbf{z}_0 = [ \\mathbf{x}_{class} ; \\mathbf{x}_{p}^1\\mathbf{E} ; \\mathbf{x}_{p}^2\\mathbf{E} ; \\dots ; \\mathbf{x}_{p}^N\\mathbf{E} ] + \\mathbf{E}_{pos} $$

Where:
- $\\mathbf{E} \\in \\mathbb{R}^{(P^2 \\cdot C) \\times D}$ is the patch embedding projection.
- $\\mathbf{x}_{class}$ is a special learnable classification token, identical to the `[CLS]` token in BERT, prepended to the sequence. Its state at the output of the transformer encoder serves as the global image representation.
- $\\mathbf{E}_{pos} \\in \\mathbb{R}^{(N+1) \\times D}$ are standard learnable 1D position embeddings. Because transformers are permutation invariant, position embeddings are strictly necessary to retain spatial information.

### 11.4.2 The Multi-Head Self-Attention (MHSA) Mechanism

Once the image is a sequence of embeddings $\\mathbf{z}_0$, it is passed through $L$ layers of the Transformer Encoder. The core of each layer is the **Multi-Head Self-Attention** mechanism.

For a given embedding sequence $\\mathbf{Z}$, it is projected into Queries $\\mathbf{Q}$, Keys $\\mathbf{K}$, and Values $\\mathbf{V}$:
$$ \\mathbf{Q} = \\mathbf{Z}\\mathbf{W}_Q, \\quad \\mathbf{K} = \\mathbf{Z}\\mathbf{W}_K, \\quad \\mathbf{V} = \\mathbf{Z}\\mathbf{W}_V $$

The self-attention computes how much every patch should "attend" to every other patch. The unscaled dot product of queries and keys yields the attention logits:

$$ \\text{Attention}(\\mathbf{Q}, \\mathbf{K}, \\mathbf{V}) = \\text{softmax}\\left(\\frac{\\mathbf{Q}\\mathbf{K}^T}{\\sqrt{D_h}}\\right) \\mathbf{V} $$

Here, $\\mathbf{Q}\\mathbf{K}^T$ forms an $N \\times N$ attention matrix. By computing this globally, ViT can link a patch in the top-left corner directly to a patch in the bottom-right corner in the very first layer, a feat impossible for early layers of a CNN.

To capture diverse structural representations (e.g., one head tracking color, another tracking edges), the attention is split into $k$ independent "heads", each operating in a subspace dimension $D_h = D/k$. The outputs are concatenated and linearly projected back to dimension $D$.

### 11.4.3 Transformer Encoder Block Architecture

A single layer $l$ of the ViT Encoder involves Layer Normalization (LN), MHSA, and an MLP block consisting of two dense layers with a GELU non-linearity. Crucially, residual (skip) connections are employed around both the MHSA and MLP blocks.

$$ \\mathbf{z}'_l = \\text{MHSA}(\\text{LN}(\\mathbf{z}_{l-1})) + \\mathbf{z}_{l-1} $$
$$ \\mathbf{z}_l = \\text{MLP}(\\text{LN}(\\mathbf{z}'_l)) + \\mathbf{z}'_l $$

This pre-norm architecture (applying Layer Normalization *before* the operation) is essential for stabilizing the training of very deep transformers.

```python
import torch
import torch.nn as nn

class PatchEmbedding(nn.Module):
    def __init__(self, img_size=224, patch_size=16, in_c=3, embed_dim=768):
        super().__init__()
        self.img_size = img_size
        self.patch_size = patch_size
        self.n_patches = (img_size // patch_size) ** 2
        
        # Equivalent to linear projection of flattened patches
        self.proj = nn.Conv2d(in_c, embed_dim, kernel_size=patch_size, stride=patch_size)

    def forward(self, x):
        # x: (B, C, H, W)
        x = self.proj(x)  # (B, embed_dim, H/P, W/P)
        x = x.flatten(2)  # (B, embed_dim, N)
        x = x.transpose(1, 2)  # (B, N, embed_dim)
        return x

class VisionTransformer(nn.Module):
    def __init__(self, img_size=224, patch_size=16, in_c=3, n_classes=1000, embed_dim=768, depth=12, num_heads=12):
        super().__init__()
        self.patch_embed = PatchEmbedding(img_size, patch_size, in_c, embed_dim)
        
        self.cls_token = nn.Parameter(torch.zeros(1, 1, embed_dim))
        self.pos_embed = nn.Parameter(torch.zeros(1, 1 + self.patch_embed.n_patches, embed_dim))
        self.pos_drop = nn.Dropout(p=0.1)

        # PyTorch built-in TransformerEncoder
        encoder_layer = nn.TransformerEncoderLayer(
            d_model=embed_dim, 
            nhead=num_heads, 
            dim_feedforward=embed_dim*4, 
            activation="gelu",
            batch_first=True
        )
        self.blocks = nn.TransformerEncoder(encoder_layer, num_layers=depth)
        
        self.norm = nn.LayerNorm(embed_dim)
        self.head = nn.Linear(embed_dim, n_classes)

    def forward(self, x):
        B = x.shape[0]
        x = self.patch_embed(x)
        
        # Expand CLS token for batch size
        cls_tokens = self.cls_token.expand(B, -1, -1)
        x = torch.cat((cls_tokens, x), dim=1)
        
        x = x + self.pos_embed
        x = self.pos_drop(x)
        
        x = self.blocks(x)
        
        # Take the state of the CLS token
        x = self.norm(x[:, 0])
        x = self.head(x)
        return x
```

### 11.4.4 The Inductive Bias Trade-off

Why didn't Vision Transformers immediately replace CNNs for all tasks? The answer lies in **Inductive Bias**.

CNNs have a strong inductive bias towards locality and translation invariance. They inherently "assume" that neighboring pixels are highly correlated and that a cat is a cat regardless of where it appears in the image. This bias allows CNNs to learn effective features very quickly from small datasets.

Vision Transformers have almost zero inductive bias about the structure of an image. A ViT must *learn* from scratch that images are 2D, that local patches are correlated, and how to track spatial translation. As a result:
- When trained on moderately sized datasets (like ImageNet-1k, which has 1.2 million images), ViTs often underperform CNNs (like ResNet) because they overfit.
- When trained on colossal datasets (like JFT-300M with 300 million images), ViTs surpass CNNs. With enough data, the Transformer's lack of restriction allows it to learn representations that are fundamentally superior to the constraints imposed by convolutions.

To mitigate this data-hunger, newer hybrid architectures like **Swin Transformer** re-introduce some localized structure by calculating attention only within local spatial windows and shifting these windows across layers, combining the best of CNN inductive biases with Transformer scaling capabilities.

---

## 11.5 Summary

Advanced Computer Vision relies on highly specialized architectures tailored to specific localization and classification requirements.
- **Object Detection** has evolved from slow region proposal generation (R-CNN) to unified, high-speed regression pipelines (YOLO).
- **Segmentation** moves from bounding boxes to pixel-level delineations. The U-Net encoder-decoder structure is crucial for combining deep semantic context with precise spatial resolution.
- **Vision Transformers** represent a fundamental paradigm shift, modeling images as sequences of patches. By leveraging Multi-Head Self-Attention, they capture global context immediately, outscaling CNNs when backed by massive computational and data resources.

In the next chapter, we will cross the boundary from Computer Vision into Natural Language Processing, where the Transformer architecture originally debuted. We will explore Word Embeddings, Recurrent Neural Networks, and eventually trace how the attention mechanism disrupted NLP just as it is now disrupting vision.
"""

markdown_part2 = """

---

### Appendix A: Detailed Mathematics of Anchor Box Matching

A critical aspect of object detection algorithms like Faster R-CNN and YOLO is the assignment of ground-truth boxes to anchor boxes during training. This assignment is based heavily on IoU metrics. 

Given an anchor box $a$ and a ground-truth box $g$, the matching procedure typically follows these rules:
1. Identify the ground-truth box with the highest IoU for every anchor box.
2. If the maximum IoU $> \\theta_{pos}$ (often 0.7), assign it as a positive sample.
3. If the maximum IoU $< \\theta_{neg}$ (often 0.3), assign it as a negative sample (background).
4. If the IoU falls between $\\theta_{neg}$ and $\\theta_{pos}$, the anchor is generally ignored during gradient updates to maintain clear decision boundaries.

The regression targets $(t_x, t_y, t_w, t_h)$ for a matched positive anchor are parameterized as:

$$ t_x = \\frac{g_x - a_x}{a_w}, \\quad t_y = \\frac{g_y - a_y}{a_h} $$
$$ t_w = \\log\\left(\\frac{g_w}{a_w}\\right), \\quad t_h = \\log\\left(\\frac{g_h}{a_h}\\right) $$

Where $(g_x, g_y, g_w, g_h)$ are the center coordinates, width, and height of the ground truth box, and $(a_x, a_y, a_w, a_h)$ are those of the anchor box. Using logarithms for width and height ensures that the network predictions can map from $(-\\infty, \\infty)$ into strictly positive dimensions for bounding boxes.

### Appendix B: Advanced Loss Functions for Object Detection

While standard L1 or L2 loss functions were used in early object detectors, modern detectors often use specialized loss functions that directly optimize IoU.

**GIoU (Generalized Intersection over Union):**
Standard IoU has a gradient of zero when boxes do not overlap, meaning the network receives no learning signal to move the boxes closer. GIoU addresses this by finding the smallest enclosing convex hull $C$ that contains both the predicted and ground truth boxes.
$$ GIoU = IoU - \\frac{|C \\setminus (B_p \\cup B_{gt})|}{|C|} $$
GIoU provides a continuous gradient that encourages non-overlapping boxes to move toward each other.

**Focal Loss (RetinaNet):**
One-stage detectors face an extreme class imbalance: millions of background anchor boxes for every few positive object boxes. Standard Cross-Entropy loss gets overwhelmed by the easily classified background examples. Focal Loss adds a modulating factor $(1 - p_t)^\\gamma$ to the standard cross entropy loss.
$$ FL(p_t) = -\\alpha_t (1 - p_t)^\\gamma \\log(p_t) $$
This dramatically down-weights the loss contributed by well-classified background examples, forcing the network to focus on hard, misclassified examples.

These advanced theoretical concepts form the robust foundation upon which modern, state-of-the-art vision models are built and optimized for real-world inference.
"""

full_content = markdown_part1 + markdown_part2

with open(TARGET_FILE, "w", encoding="utf-8") as f:
    f.write(full_content)

print(f"File {TARGET_FILE} generated successfully with {len(full_content.split())} words.")
