r"""
===========================================================================
Module: 03-topic-modeling
===========================================================================

Description:
    A textbook-grade, interactive Python lesson on Topic Modeling, covering
    the theoretical foundations, mathematical underpinnings, algorithms, 
    and from-scratch implementations of major topic modeling techniques:
    1. Latent Semantic Analysis (LSA)
    2. Non-Negative Matrix Factorization (NMF)
    3. Latent Dirichlet Allocation (LDA)

Learning Objectives:
    1. Understand the purpose of Topic Modeling in Natural Language Processing (NLP).
    2. Master the mathematical formulations: Singular Value Decomposition (SVD),
       Multiplicative Update Rules for NMF, and Collapsed Gibbs Sampling for LDA.
    3. Implement vectorization strategies: Bag-of-Words (BoW) and TF-IDF.
    4. Analyze time and space complexities of different topic modeling approaches.
    5. Solve a common NLP interview challenge involving topic similarity.

---------------------------------------------------------------------------
1. Theoretical Background
---------------------------------------------------------------------------
Topic Modeling is an unsupervised machine learning technique used to discover
abstract "topics" that occur in a collection of documents (a corpus). It is
based on the intuition that documents are mixtures of topics, and topics are
mixtures of words.

Mathematical Formulations:

A. Latent Semantic Analysis (LSA)
    LSA assumes that words that are close in meaning will occur in similar pieces
    of text. It uses Singular Value Decomposition (SVD) to reduce the dimensionality
    of the Document-Term Matrix (DTM).
    
    Given a matrix $X \in \mathbb{R}^{d \times v}$ (d = documents, v = vocab),
    SVD factors $X$ into:
        $X = U \Sigma V^T$
    Where:
        $U \in \mathbb{R}^{d \times d}$: Document-topic matrix.
        $\Sigma \in \mathbb{R}^{d \times v}$: Diagonal matrix of singular values.
        $V^T \in \mathbb{R}^{v \times v}$: Topic-term matrix.
        
    By keeping only the top $k$ singular values (Truncated SVD), we get an
    approximation $X_k$ that captures the most important latent structures.

B. Non-Negative Matrix Factorization (NMF)
    NMF factors a non-negative matrix $V$ into two non-negative matrices $W$ and $H$:
        $V \approx W \times H$
    Where:
        $V \in \mathbb{R}_{+}^{d \times v}$: Document-Term Matrix
        $W \in \mathbb{R}_{+}^{d \times k}$: Document-Topic weights
        $H \in \mathbb{R}_{+}^{k \times v}$: Topic-Term weights
    
    NMF is solved via iterative Multiplicative Update Rules:
        $H_{ij} \leftarrow H_{ij} \frac{(W^T V)_{ij}}{(W^T W H)_{ij}}$
        $W_{ij} \leftarrow W_{ij} \frac{(V H^T)_{ij}}{(W H H^T)_{ij}}$
    
    The non-negativity constraint leads to a parts-based representation, which
    is often more interpretable than LSA.

C. Latent Dirichlet Allocation (LDA)
    LDA is a generative probabilistic model. It assumes that:
    1. There are $K$ topics, each being a multinomial distribution over the vocabulary $\beta_k \sim \text{Dirichlet}(\eta)$.
    2. Each document $d$ has a multinomial topic distribution $\theta_d \sim \text{Dirichlet}(\alpha)$.
    3. Each word $w_{d,n}$ in doc $d$ is generated by sampling a topic $z_{d,n} \sim \text{Multinomial}(\theta_d)$
       and then sampling a word $w_{d,n} \sim \text{Multinomial}(\beta_{z_{d,n}})$.
       
    Inference is commonly done using Collapsed Gibbs Sampling, updating the topic 
    assignment of each word based on the conditional probability:
        $P(z_{i} = k \mid z_{-i}, w) \propto \left( n_{d, k}^{-i} + \alpha \right) \frac{n_{k, w_i}^{-i} + \eta}{n_{k, \cdot}^{-i} + V \eta}$

---------------------------------------------------------------------------
2. Big-O Complexity Analysis
---------------------------------------------------------------------------
Let `d` = number of documents, `v` = vocabulary size, `n` = total words, `k` = topics.

1. LSA (Truncated SVD):
   - Time: $O(d \cdot v \cdot k)$ using randomized SVD algorithms, or $O(\min(d^2 v, d v^2))$ for full.
   - Space: $O(d \cdot v)$ for dense DTM, much less for sparse matrices.

2. NMF:
   - Time: $O(i \cdot d \cdot v \cdot k)$ where $i$ is the number of iterations.
   - Space: $O(d \cdot k + k \cdot v)$.

3. LDA (Gibbs Sampling):
   - Time: $O(i \cdot n \cdot k)$ where $i$ is iterations, $n$ is total words in corpus.
   - Space: $O(d \cdot k + k \cdot v + n)$ to store counts and assignments.

---------------------------------------------------------------------------
3. Real-World Applications
---------------------------------------------------------------------------
- Recommender Systems (Content-based filtering using topic profiles).
- Document Clustering and Categorization.
- Trend Analysis in social media, news, and academic papers.
- Feature Engineering for downstream NLP tasks (e.g., classification).
- Information Retrieval and Semantic Search.

===========================================================================
"""

import math
import random
import re
from collections import defaultdict, Counter
from typing import List, Dict, Tuple, Set, Optional, Any, Callable

# Using numpy for matrix operations (SVD, NMF)
import numpy as np


class TextPreprocessor:
    """
    A foundational utility for preprocessing textual data.
    In real-world NLP, preprocessing is as crucial as the modeling itself.
    """
    
    def __init__(self, stop_words: Optional[Set[str]] = None):
        """
        Initializes the preprocessor with an optional set of stop words.
        
        Time Complexity: O(1)
        Space Complexity: O(S) where S is the number of stop words.
        """
        self.stop_words = stop_words or {
            "a", "about", "above", "after", "again", "against", "all", "am", "an", "and", 
            "any", "are", "as", "at", "be", "because", "been", "before", "being", "below", 
            "between", "both", "but", "by", "could", "did", "do", "does", "doing", "down", 
            "during", "each", "few", "for", "from", "further", "had", "has", "have", 
            "having", "he", "he'd", "he'll", "he's", "her", "here", "here's", "hers", 
            "herself", "him", "himself", "his", "how", "how's", "i", "i'd", "i'll", 
            "i'm", "i've", "if", "in", "into", "is", "it", "it's", "its", "itself", 
            "let's", "me", "more", "most", "my", "myself", "nor", "of", "on", "once", 
            "only", "or", "other", "ought", "our", "ours", "ourselves", "out", "over", 
            "own", "same", "she", "she'd", "she'll", "she's", "should", "so", "some", 
            "such", "than", "that", "that's", "the", "their", "theirs", "them", 
            "themselves", "then", "there", "there's", "these", "they", "they'd", 
            "they'll", "they're", "they've", "this", "those", "through", "to", "too", 
            "under", "until", "up", "very", "was", "we", "we'd", "we'll", "we're", 
            "we've", "were", "what", "what's", "when", "when's", "where", "where's", 
            "which", "while", "who", "who's", "whom", "why", "why's", "with", "would", 
            "you", "you'd", "you'll", "you're", "you've", "your", "yours", "yourself", 
            "yourselves", "the", "is", "in", "it", "to", "of", "and", "a"
        }

    def tokenize(self, text: str) -> List[str]:
        """
        Converts text to lowercase, removes punctuation, and splits into tokens.
        Filters out stop words and short words.
        
        Time Complexity: O(N) where N is the length of the string.
        Space Complexity: O(T) where T is the number of tokens.
        """
        # Lowercase and replace non-alphanumeric with spaces
        text = text.lower()
        text = re.sub(r'[^a-z0-9\s]', ' ', text)
        
        tokens = text.split()
        
        # Filter tokens
        filtered = [
            token for token in tokens 
            if token not in self.stop_words and len(token) > 2
        ]
        
        return filtered


class CorpusManager:
    """
    Manages the document collection, builds vocabulary, and creates 
    Document-Term Matrices (DTMs) using Bag-of-Words (BoW) or TF-IDF.
    """
    
    def __init__(self):
        self.vocab: Dict[str, int] = {}
        self.reverse_vocab: Dict[int, str] = {}
        self.doc_frequencies: Dict[str, int] = defaultdict(int)
        self.num_docs = 0
        self.preprocessor = TextPreprocessor()
        
        # Store tokenized documents
        self.tokenized_docs: List[List[str]] = []
        
    def fit_transform(self, documents: List[str], use_tfidf: bool = False) -> np.ndarray:
        """
        Fits the vocabulary on the documents and transforms them into a DTM.
        
        Time Complexity: O(D * L) where D is number of docs, L is average doc length.
        Space Complexity: O(D * V) for the dense numpy array. In practice, sparse matrices are used.
        """
        self.num_docs = len(documents)
        self.tokenized_docs = [self.preprocessor.tokenize(doc) for doc in documents]
        
        # Build vocabulary and doc frequencies
        vocab_idx = 0
        for tokens in self.tokenized_docs:
            unique_tokens = set(tokens)
            for token in unique_tokens:
                self.doc_frequencies[token] += 1
                if token not in self.vocab:
                    self.vocab[token] = vocab_idx
                    self.reverse_vocab[vocab_idx] = token
                    vocab_idx += 1
                    
        vocab_size = len(self.vocab)
        
        # Create Document-Term Matrix (Dense for educational simplicity)
        dtm = np.zeros((self.num_docs, vocab_size), dtype=np.float64)
        
        for doc_id, tokens in enumerate(self.tokenized_docs):
            term_counts = Counter(tokens)
            for token, count in term_counts.items():
                if token in self.vocab:
                    col_idx = self.vocab[token]
                    
                    if use_tfidf:
                        # Term Frequency (TF)
                        tf = count / len(tokens) if tokens else 0
                        # Inverse Document Frequency (IDF) - smoothed
                        idf = math.log((1 + self.num_docs) / (1 + self.doc_frequencies[token])) + 1
                        dtm[doc_id, col_idx] = tf * idf
                    else:
                        # Bag of Words (BoW) count
                        dtm[doc_id, col_idx] = count
                        
        return dtm

    def get_feature_names(self) -> List[str]:
        """Returns the vocabulary ordered by index."""
        return [self.reverse_vocab[i] for i in range(len(self.vocab))]


# =========================================================================
# Topic Modeling Implementations
# =========================================================================

class LSAModel:
    """
    Latent Semantic Analysis (LSA) implementation using Singular Value Decomposition.
    Best used with TF-IDF matrices.
    """
    
    def __init__(self, num_topics: int):
        self.num_topics = num_topics
        self.U: Optional[np.ndarray] = None
        self.Sigma: Optional[np.ndarray] = None
        self.VT: Optional[np.ndarray] = None
        
    def fit(self, X: np.ndarray) -> np.ndarray:
        """
        Fits the LSA model using NumPy's SVD.
        
        Args:
            X: Document-Term matrix (usually TF-IDF). Shape (D, V).
            
        Returns:
            Document-Topic matrix of shape (D, K).
        """
        print("[LSA] Performing Singular Value Decomposition...")
        # Full SVD
        # U shape: (D, D), S shape: (min(D, V),), VT shape: (V, V)
        U_full, S_full, VT_full = np.linalg.svd(X, full_matrices=False)
        
        # Truncate to num_topics (k)
        k = self.num_topics
        self.U = U_full[:, :k]
        self.Sigma = np.diag(S_full[:k])
        self.VT = VT_full[:k, :]
        
        # Document-topic matrix is U * Sigma
        doc_topic = np.dot(self.U, self.Sigma)
        return doc_topic
        
    def get_topics(self, feature_names: List[str], top_n: int = 5) -> List[List[Tuple[str, float]]]:
        """
        Extracts the top words for each topic.
        """
        topics = []
        for topic_idx, topic_vector in enumerate(self.VT):
            # Sort topic weights in descending order
            top_indices = np.argsort(topic_vector)[::-1][:top_n]
            topic_words = [(feature_names[i], topic_vector[i]) for i in top_indices]
            topics.append(topic_words)
        return topics


class NMFModel:
    """
    Non-Negative Matrix Factorization (NMF) implementation using 
    Multiplicative Update Rules. Best used with TF-IDF matrices.
    
    Ensures all topic weights and document representations are non-negative,
    making topics highly interpretable (parts-based representation).
    """
    
    def __init__(self, num_topics: int, max_iter: int = 200, tol: float = 1e-4):
        self.num_topics = num_topics
        self.max_iter = max_iter
        self.tol = tol
        self.W: Optional[np.ndarray] = None # Document-Topic
        self.H: Optional[np.ndarray] = None # Topic-Term
        
    def fit(self, V: np.ndarray) -> np.ndarray:
        """
        Fits the NMF model using Lee & Seung's Multiplicative Update rules.
        
        Args:
            V: Document-Term matrix. Shape (D, V). All elements must be >= 0.
            
        Returns:
            W: Document-topic matrix.
        """
        print("[NMF] Initializing W and H matrices...")
        D, V_cols = V.shape
        K = self.num_topics
        
        # Random initialization with non-negative values
        np.random.seed(42)
        self.W = np.random.rand(D, K)
        self.H = np.random.rand(K, V_cols)
        
        # Add small epsilon to avoid division by zero
        eps = 1e-9
        
        print("[NMF] Starting multiplicative updates...")
        for iteration in range(self.max_iter):
            # Update H (Topic-Term matrix)
            # H = H * (W^T * V) / (W^T * W * H + eps)
            numerator_H = np.dot(self.W.T, V)
            denominator_H = np.dot(np.dot(self.W.T, self.W), self.H) + eps
            self.H *= numerator_H / denominator_H
            
            # Update W (Document-Topic matrix)
            # W = W * (V * H^T) / (W * H * H^T + eps)
            numerator_W = np.dot(V, self.H.T)
            denominator_W = np.dot(self.W, np.dot(self.H, self.H.T)) + eps
            self.W *= numerator_W / denominator_W
            
            # Compute Frobenius norm of the reconstruction error to check for convergence
            if iteration % 50 == 0:
                error = np.linalg.norm(V - np.dot(self.W, self.H), 'fro')
                # Optional: check if error change is below tol to break early
                
        return self.W

    def get_topics(self, feature_names: List[str], top_n: int = 5) -> List[List[Tuple[str, float]]]:
        """Extracts top words for each topic."""
        topics = []
        for topic_idx, topic_vector in enumerate(self.H):
            top_indices = np.argsort(topic_vector)[::-1][:top_n]
            topic_words = [(feature_names[i], topic_vector[i]) for i in top_indices]
            topics.append(topic_words)
        return topics


class LDAGibbsSampler:
    """
    Latent Dirichlet Allocation (LDA) via Collapsed Gibbs Sampling.
    This is a true probabilistic generative model. Best used with raw BoW counts.
    
    Note: For a production environment, Variational Bayes (like in Gensim) or 
    highly optimized C++ Gibbs samplers (like Mallet) are preferred. This Python
    implementation is strictly for deep educational understanding.
    """
    
    def __init__(self, num_topics: int, alpha: float = 0.1, eta: float = 0.1, max_iter: int = 100):
        self.K = num_topics
        self.alpha = alpha  # Dirichlet prior on doc-topic distribution
        self.eta = eta      # Dirichlet prior on topic-word distribution
        self.max_iter = max_iter
        
    def fit(self, tokenized_docs: List[List[str]], vocab: Dict[str, int]) -> np.ndarray:
        """
        Fits the LDA model using Collapsed Gibbs Sampling.
        
        Args:
            tokenized_docs: List of documents, where each document is a list of string tokens.
            vocab: Mapping from token to integer ID.
            
        Returns:
            Document-Topic probability matrix theta (D x K).
        """
        print("[LDA] Initializing Gibbs Sampler state...")
        D = len(tokenized_docs)
        V = len(vocab)
        K = self.K
        
        # State tracking matrices
        # n_dk[d, k] = count of words assigned to topic k in document d
        self.n_dk = np.zeros((D, K), dtype=np.int32)
        # n_kw[k, v] = count of times word v is assigned to topic k
        self.n_kw = np.zeros((K, V), dtype=np.int32)
        # n_k[k] = total words assigned to topic k
        self.n_k = np.zeros(K, dtype=np.int32)
        
        # Word assignments: list of lists storing the topic assignment for each word in each doc
        self.Z = []
        
        # Random Initialization
        random.seed(42)
        for d in range(D):
            doc_topics = []
            for w_str in tokenized_docs[d]:
                if w_str not in vocab:
                    doc_topics.append(-1) # ignore out-of-vocab
                    continue
                
                v = vocab[w_str]
                # Randomly assign initial topic
                z = random.randint(0, K - 1)
                doc_topics.append(z)
                
                # Update counts
                self.n_dk[d, z] += 1
                self.n_kw[z, v] += 1
                self.n_k[z] += 1
                
            self.Z.append(doc_topics)
            
        print("[LDA] Starting Gibbs Sampling iterations...")
        for iteration in range(self.max_iter):
            # Iterate over all documents and all words
            for d in range(D):
                for i, w_str in enumerate(tokenized_docs[d]):
                    if w_str not in vocab:
                        continue
                        
                    v = vocab[w_str]
                    z = self.Z[d][i]
                    
                    # Decrement counts (remove this word from the current topic state)
                    self.n_dk[d, z] -= 1
                    self.n_kw[z, v] -= 1
                    self.n_k[z] -= 1
                    
                    # Calculate probabilities for sampling a new topic
                    # P(z_i = k | z_-i, w) \propto 
                    #   (n_dk + alpha) * (n_kw + eta) / (n_k + V * eta)
                    
                    # Vectorized computation for all K topics
                    p_z = (self.n_dk[d, :] + self.alpha) * \
                          (self.n_kw[:, v] + self.eta) / \
                          (self.n_k + V * self.eta)
                          
                    # Normalize to form a probability distribution
                    p_z /= np.sum(p_z)
                    
                    # Sample new topic from the distribution
                    new_z = np.random.choice(K, p=p_z)
                    
                    # Assign new topic and update counts
                    self.Z[d][i] = new_z
                    self.n_dk[d, new_z] += 1
                    self.n_kw[new_z, v] += 1
                    self.n_k[new_z] += 1
            
            if (iteration + 1) % 25 == 0:
                print(f"[LDA] Completed {iteration + 1}/{self.max_iter} iterations.")
                
        # Compute final document-topic distributions (Theta)
        # theta_{d, k} = (n_{d, k} + alpha) / (\sum n_{d, \cdot} + K * alpha)
        theta = np.zeros((D, K))
        for d in range(D):
            total_doc_words = np.sum(self.n_dk[d, :])
            theta[d, :] = (self.n_dk[d, :] + self.alpha) / (total_doc_words + K * self.alpha)
            
        # Compute final topic-word distributions (Phi)
        # phi_{k, v} = (n_{k, v} + eta) / (\sum n_{k, \cdot} + V * eta)
        self.phi = np.zeros((K, V))
        for k in range(K):
            self.phi[k, :] = (self.n_kw[k, :] + self.eta) / (self.n_k[k] + V * self.eta)
            
        return theta

    def get_topics(self, feature_names: List[str], top_n: int = 5) -> List[List[Tuple[str, float]]]:
        """Extracts top words for each topic based on the Phi matrix."""
        topics = []
        for k in range(self.K):
            topic_prob = self.phi[k, :]
            top_indices = np.argsort(topic_prob)[::-1][:top_n]
            topic_words = [(feature_names[i], topic_prob[i]) for i in top_indices]
            topics.append(topic_words)
        return topics


# =========================================================================
# Interview Challenge: Document Similarity using Topic Profiles
# =========================================================================

def cosine_similarity(vec1: np.ndarray, vec2: np.ndarray) -> float:
    """
    Helper function to compute cosine similarity between two vectors.
    """
    dot_product = np.dot(vec1, vec2)
    norm1 = np.linalg.norm(vec1)
    norm2 = np.linalg.norm(vec2)
    if norm1 == 0 or norm2 == 0:
        return 0.0
    return dot_product / (norm1 * norm2)

def interview_challenge_similar_documents(
    query_doc_idx: int, 
    doc_topic_matrix: np.ndarray, 
    top_k: int = 3
) -> List[Tuple[int, float]]:
    """
    Interview Challenge:
    Given a Document-Topic matrix (where rows are documents and columns are 
    topic distributions or weights), find the Top-K most similar documents 
    to a given query document.
    
    Approach:
    1. Extract the topic vector for the query document.
    2. Compute the cosine similarity between the query vector and all other doc vectors.
    3. Sort by similarity descending.
    4. Return the top_k indices and their similarity scores (excluding the query doc itself).
    
    Time Complexity: O(D * K + D log D) where D is number of docs, K is number of topics.
    Space Complexity: O(D) to store similarity scores.
    """
    print("\n--- Running Interview Challenge: Topic-based Document Similarity ---")
    
    D = doc_topic_matrix.shape[0]
    if query_doc_idx < 0 or query_doc_idx >= D:
        raise ValueError("Invalid query document index.")
        
    query_vector = doc_topic_matrix[query_doc_idx]
    
    similarities = []
    for d in range(D):
        if d == query_doc_idx:
            continue
        sim = cosine_similarity(query_vector, doc_topic_matrix[d])
        similarities.append((d, sim))
        
    # Sort descending by similarity score
    similarities.sort(key=lambda x: x[1], reverse=True)
    
    return similarities[:top_k]


# =========================================================================
# Execution and Demonstrations
# =========================================================================

def print_topics(model_name: str, topics: List[List[Tuple[str, float]]]):
    """Utility to pretty-print topics."""
    print(f"\n[{model_name}] Discovered Topics:")
    for i, topic_words in enumerate(topics):
        word_str = ", ".join([f"{word} ({weight:.3f})" for word, weight in topic_words])
        print(f"  Topic {i+1}: {word_str}")


def run_demonstration():
    """
    End-to-end pipeline demonstrating Preprocessing, DTM building, 
    LSA, NMF, LDA, and Document Similarity.
    """
    
    # 1. Toy Corpus representing 3 distinct underlying themes:
    #    - Space / Astronomy
    #    - Tech / Programming
    #    - Animals / Pets
    documents = [
        # Space
        "The telescope revealed new galaxies and stars in deep space.",
        "Astronomy is the study of celestial bodies like planets and stars.",
        "NASA launched a new satellite into space orbit.",
        "The black hole in the center of the galaxy is massive.",
        
        # Tech
        "Python is a great programming language for software development.",
        "Object oriented programming helps structure complex software architecture.",
        "Developers write code using various programming languages.",
        "Cloud computing is transforming how we deploy software code.",
        
        # Pets
        "My cat loves to play with yarn and sleep all day.",
        "Dogs are known as man's best friend and loyal pets.",
        "Veterinarians take care of sick animals, including cats and dogs.",
        "Feeding your pet a healthy diet is important for its long life."
    ]
    
    num_topics = 3  # We expect the 3 themes to be discovered
    
    print("========== TOPIC MODELING MASTERCLASS ==========")
    print(f"Corpus Size: {len(documents)} documents")
    print(f"Target Topics (K): {num_topics}")
    
    # 2. Preprocessing & DTM creation
    print("\n--- 1. Corpus Preprocessing & Feature Extraction ---")
    corpus_manager = CorpusManager()
    
    # TF-IDF matrix is preferred for LSA and NMF
    tfidf_dtm = corpus_manager.fit_transform(documents, use_tfidf=True)
    # BoW matrix is strictly required for generative count models like LDA
    bow_dtm = corpus_manager.fit_transform(documents, use_tfidf=False)
    
    vocab_names = corpus_manager.get_feature_names()
    print(f"Vocabulary Size: {len(vocab_names)} unique tokens")
    
    # 3. Latent Semantic Analysis (LSA)
    print("\n--- 2. Latent Semantic Analysis (LSA) via SVD ---")
    lsa_model = LSAModel(num_topics=num_topics)
    lsa_doc_topic = lsa_model.fit(tfidf_dtm)
    print_topics("LSA", lsa_model.get_topics(vocab_names, top_n=4))
    
    # 4. Non-Negative Matrix Factorization (NMF)
    print("\n--- 3. Non-Negative Matrix Factorization (NMF) ---")
    nmf_model = NMFModel(num_topics=num_topics, max_iter=200)
    nmf_doc_topic = nmf_model.fit(tfidf_dtm)
    print_topics("NMF", nmf_model.get_topics(vocab_names, top_n=4))
    
    # 5. Latent Dirichlet Allocation (LDA)
    print("\n--- 4. Latent Dirichlet Allocation (LDA) via Gibbs Sampling ---")
    lda_model = LDAGibbsSampler(num_topics=num_topics, alpha=0.1, eta=0.1, max_iter=100)
    # LDA expects the raw tokenized docs mapped to vocab
    lda_doc_topic = lda_model.fit(corpus_manager.tokenized_docs, corpus_manager.vocab)
    print_topics("LDA", lda_model.get_topics(vocab_names, top_n=4))
    
    # 6. Interview Challenge (Document Similarity)
    # Let's find documents similar to document 0 (Space) using the NMF representations
    query_idx = 0
    print(f"\nQuery Document ({query_idx}): '{documents[query_idx]}'")
    
    top_similar = interview_challenge_similar_documents(
        query_doc_idx=query_idx, 
        doc_topic_matrix=nmf_doc_topic, 
        top_k=2
    )
    
    for rank, (doc_idx, sim_score) in enumerate(top_similar, 1):
        print(f"  Rank {rank}: Doc {doc_idx} (Score: {sim_score:.4f}) -> '{documents[doc_idx]}'")


def run_tests():
    """Unit tests to validate correctness of the math components."""
    print("\n--- Running Unit Tests ---")
    
    # Test Cosine Similarity
    v1 = np.array([1, 0, 0])
    v2 = np.array([1, 0, 0])
    v3 = np.array([0, 1, 0])
    
    assert math.isclose(cosine_similarity(v1, v2), 1.0), "Cosine similarity identity failed."
    assert math.isclose(cosine_similarity(v1, v3), 0.0), "Cosine similarity orthogonal failed."
    
    # Test Preprocessor
    prep = TextPreprocessor(stop_words={"the", "is", "a"})
    tokens = prep.tokenize("The quick brown Fox is a fast animal!")
    assert tokens == ["quick", "brown", "fox", "fast", "animal"], f"Tokenizer failed: {tokens}"
    
    print("All tests passed successfully!")


if __name__ == "__main__":
    run_demonstration()
    run_tests()
    print("\n========== END OF TOPIC MODELING MASTERCLASS ==========\n")
